install:
  - 'sudo apt-get update'
  - 'sudo apt-get install libssl-dev'
  - 'sudo apt-get install curl'
  - 'sudo apt-get install git-ftp'

script:
  - 'git ftp init -vv --user $FTP_USER --passwd $FTP_PASSWORD "ftp://blockui.io:21/public_html/blocks"'
  #- 'git ftp catchup -vv --ftp-ssl --disable-epsv --ftp-pasv --no-certificate-check --user $FTP_USER --passwd $FTP_PASSWORD "ftp://blockui.io:21/public_html/blocks"'
  #- 'git ftp push -vv --user $FTP_USER --passwd $FTP_PASSWORD "sftp://blockui.io:1157/public_html/blocks"'

