install:
  - 'sudo apt-get update'
  - 'sudo apt-get install libssl-dev'
  - 'sudo apt-get install lftp'

script:
  - 'lftp -c "open -u $FTP_USER,$FTP_PASSWORD ftp.blockui.io; set ssl:verify-certificate no; mirror -R ./ /public_html/blocks"'